### ISSUE TITLE
AttributeError: 'QgsRasterLayer' object has no attribute 'select'

### ISSUE THREAD

**Issue by nzfarmer1** [felferrari/MultipleLayerSelection#1]
Use case:

Click on any part in the canvas

Result:

Traceback (most recent call last):
  File "/Users/andrew/.qgis2/python/plugins/MultipleLayerSelection/MultiLayerSelection.py", line 25, in canvasPressEvent
    layer.select(lRect, False)
AttributeError: 'QgsRasterLayer' object has no attribute 'select'

Also
AttributeError: 'QgsRasterLayer' object has no attribute 'deactivate' on exiting.

Environment:
Mac OSX 10.95
QGIS 2.6.0 Brighton

**Comment by nzfarmer1** [comment]
Need to check layer type first ...?

**Comment by lcoandrade** [comment]
Yes, we should check the layer type do avoid this problem. Fortunately it's not a blocking issue. We'll fix this. Thanks.

**Comment by lcoandrade** [comment]
Problem solved.
